---
title: "Analysis on Dota2 hero Invoker"
output: html_document
---


####Load packages.
```{r load packages,message=FALSE}
suppressWarnings(library(dplyr))
suppressWarnings(library(tidyr))
suppressWarnings(library(RCurl))
suppressWarnings(library(jsonlite))
suppressWarnings(library(RSQLite))
suppressWarnings(library(ggplot2))
suppressWarnings(library(png))
suppressWarnings(library(grid))
```

  
####Load my Steam key. 
In order to use Dota2 API, you need to have a Steam account and [apply for a key](https://steamcommunity.com/dev).

```{r}
steam_key=readRDS(file="E:/dota_data/steam_key.rds")
```


####Load data from SQLite database.
```{r sql, cache=T}
db = dbConnect(SQLite(), "D:/DataSci_tools/Git_Repo/dota2/dota_6.86f.sqlite3")

match = dbReadTable(db,'match')    #match info
player = dbReadTable(db,'player')    #player info for each match
ability_up = dbReadTable(db,'ability_up')    #ability upgrade information for each player

dbDisconnect(db)
```


####Quick look of the datasets
```{r data info}
head(match)
head(player,10)
head(ability_up)
```


####Acquire a list of heros using the API.
```{r}
inv_id=74    # invoker, http://api.steampowered.com/IEconDOTA2_205790/GetHeroes/v0001/?language=en&key=steam_key

hero_json = fromJSON(getURL(paste0("http://api.steampowered.com/IEconDOTA2_205790/GetHeroes/v0001/?language=en&key=",steam_key)))
hero_names = gsub('npc_dota_hero_','',hero_json$result$heroes$name)
hero_names = data.frame(id = hero_json$result$heroes$id,name = hero_names,stringsAsFactors = F)
head(hero_names)
```

```{r subset,cache=TRUE}
inv_matchid = filter(player,hero_id==inv_id) %>% select(match_id) %>% unlist

inv_match = filter(match,match_id%in%inv_matchid)
inv_player = filter(player,match_id%in%inv_matchid)
inv_ability = filter(ability_up,match_id%in%inv_matchid)
```

```{r,cache=TRUE}
#summarize heros info for each game, spread rows to columns
game_info = inv_player %>% select(match_id,player_slot,hero_id) %>% mutate(team = ifelse(player_slot<5,'radiant','dire')) %>%
    group_by(match_id,team) %>%
    mutate(has_invoker= any(hero_id==inv_id),count=1)

inv_friend = game_info %>% filter(has_invoker) %>% select(-player_slot) %>%
    spread(key = hero_id,value = count,fill = 0)
names(inv_friend)[-(1:3)] = paste0('friend_',names(inv_friend)[-(1:3)])

inv_friend = inv_friend %>% group_by(match_id,team) %>% summarise_each_(funs(mean(.,na.rm=T)),names(inv_friend)[-(1:3)]) %>% select(-friend_74)  #remove invoker from the friend list


inv_enemy = game_info %>% filter(!has_invoker) %>% select(-player_slot) %>%
    spread(key = hero_id,value = count,fill = 0)
names(inv_enemy)[-(1:3)] = paste0('enemy_',names(inv_enemy)[-(1:3)])

inv_enemy = inv_enemy %>% group_by(match_id,team) %>% summarise_each_(funs(mean(.,na.rm=T)),names(inv_enemy)[-(1:3)]) %>% select(-team)

game_info_sum = inner_join(inv_friend,inv_enemy,by='match_id')


#combine
match_info_comb = inner_join(match,game_info_sum,by='match_id')

inv_win = match_info_comb %>% select(match_id,radiant_win,team,friend_1:enemy_113) %>% 
    filter((radiant_win&team=='radiant') | (!radiant_win&team!='radiant')) %>%
    summarise_each_(funs(sum),vars=c(names(inv_friend)[-(1:3)],names(inv_enemy)[-(1:3)]))


#total number of games for each hero
game_totalN = match_info_comb %>% summarise_each_(funs(sum),vars=c(names(inv_friend)[-(1:3)],names(inv_enemy)[-(1:3)]))


inv_friend_win = t(select(inv_win,starts_with('friend'))/select(game_totalN,starts_with('friend')))
inv_friend_win = data.frame(number = row.names(inv_friend_win),win_freq = inv_friend_win,totalN = unlist(select(game_totalN,starts_with('friend'))),group='friend')
inv_friend_win = inv_friend_win[order(inv_friend_win$win_freq,decreasing = T),]


inv_enemy_win = t(select(inv_win,starts_with('enemy'))/select(game_totalN,starts_with('enemy')))
inv_enemy_win = data.frame(number = row.names(inv_enemy_win),win_freq = inv_enemy_win,totalN = unlist(select(game_totalN,starts_with('enemy'))),group='enemy')
inv_enemy_win = inv_enemy_win[order(inv_enemy_win$win_freq),]
```



```{r}
p1_data = rbind(inv_friend_win[1:10,],inv_enemy_win[10:1,]) %>% mutate(id = as.integer(gsub('.*_','',number))) %>% inner_join(hero_names,by='id')
p1_data = p1_data %>% mutate(name_f = ifelse(group=='friend',paste0(name,'_f'),paste0(name,'_e')))    #add suffix
p1_data$name_f <- factor(p1_data$name_f, levels = p1_data$name_f[order(p1_data$win_freq,decreasing = T)])
ggplot(aes(x=name_f,y=win_freq,fill=group),data=p1_data) + geom_hline(yintercept=0.5,col='blue',linetype='dashed') + geom_bar(stat = "identity") 
```


```{r,fig.height=4,fig.width=10,echo=FALSE}
for(i in 1:10){
    grid.raster(readPNG(paste0('D:/DataSci_tools/Git_Repo/dota2/205x115/',p1_data$name[i],'_lg.png')),x=i/12,height=.1)
}
```

```{r,fig.height=4,fig.width=10,echo=FALSE}
for(i in 20:11){
    grid.raster(readPNG(paste0('D:/DataSci_tools/Git_Repo/dota2/205x115/',p1_data$name[i],'_lg.png')),x=(21-i)/12,height=.1)
}
```


###

```{r,fig.height=4,fig.width=10,echo=FALSE}
for(i in 20:11){
    grid.raster(readPNG(paste0('D:/DataSci_tools/Git_Repo/dota2/205x115/',p1_data$name[i],'_lg.png')),x=(21-i)/12,height=.1)
}
```


```{r,cache=TRUE}
inv_slot = inv_player %>% filter(hero_id==inv_id) %>% select(match_id,player_slot)
inv_ability_only = inner_join(inv_ability,inv_slot,by=names(inv_slot))

inv_ab_lvl9  = inv_ability_only %>% group_by(match_id) %>%
    mutate(lvl_max = max(level)) %>% filter(lvl_max>10,level<10) %>%
    group_by(match_id,ability) %>% tally %>% spread(key=ability,value=n,fill=0)

names(inv_ab_lvl9) = c('match_id','quas','wex','exort','invoke')
head(inv_ab_lvl9)

inv_ab_lvl9 = inv_ab_lvl9 %>% mutate(inv_class=ifelse(wex<=1,'ice_fire',ifelse(exort<=1,'ice_thunder',ifelse(quas<=1,'fire_thunder','other'))))
table(inv_ab_lvl9$inv_class)
filter(inv_ab_lvl9,inv_class=='other')


match_info_comb = inner_join(match_info_comb,inv_ab_lvl9,by='match_id')

inv_win_class = match_info_comb %>% select(match_id,radiant_win,team,inv_class) %>%
    mutate(inv_win = (radiant_win&team=='radiant') | (!radiant_win&team!='radiant')) %>%
    group_by(inv_class,inv_win) %>% tally %>% group_by(inv_class) %>% mutate(total_n = sum(n),freq=n/total_n) %>%
    filter(inv_win)
```


```{r}
inv_win_class
ggplot(aes(x=inv_class,y=freq),data=inv_win_class) + geom_hline(yintercept=0.5,col='blue',linetype='dashed') + geom_bar(stat = "identity")
```

